[package]
name = "thrustcurve-api"
version = "0.1.0"
edition = "2018"

[dependencies]
hyper = { version = "^0.14", features = ["client", "http2", "tcp"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
paste = "1.0"